name: "Nya Desktop Application"

on:
  push:
    branches:
      - nya
    tags:
      - "v*"
  pull_request:
    branches:
      - nya

jobs:
  prepare:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.ver.outputs.tag }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/hoppscotch-desktop/src-tauri/tauri.conf.json

      - name: Prepare version tag
        id: ver
        run: echo "tag=$(jq .version packages/hoppscotch-desktop/src-tauri/tauri.conf.json | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Prepare release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          name: "Hoppscotch (nya) v${{ steps.ver.outputs.tag }}"
          body: "请检视资源列表以下载并安装此版本应用程序。"
          draft: true

  build:
    needs: [prepare]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
            identifier: "macos-aarch64"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
            identifier: "macos-amd64"
          - platform: "ubuntu-22.04"
            args: ""
            identifier: "linux"
          - platform: "windows-latest"
            args: ""
            identifier: "windows"

    runs-on: ${{ matrix.platform }}
    steps:

      #############################################
      ##                 Prepare                 ##
      #############################################

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Linux only)
        if: matrix.identifier == 'linux'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      #############################################
      ##                  Build                  ##
      #############################################

      - name: Prepare dotenv for backend
        run: |
          cp .env.example .env
          cp .env.example ./packages/hoppscotch-backend/.env

      - name: Prepare prisma for windows # Otherwise it's just not working
        if: matrix.platform == 'windows-latest'
        run: |
          cd ./packages/hoppscotch-backend/
          pnpm install --frozen-lockfile --ignore-scripts
          pnpm exec prisma generate

      - name: Install all dependencies
        run: pnpm install --frozen-lockfile --force

      - name: Prepare frontend assets
        run: |
          cd ./packages/hoppscotch-selfhost-web
          pnpm install
          pnpm generate

      - name: Bundle frontend assets
        run: |
          cd ./packages/hoppscotch-desktop/crates/webapp-bundler
          cargo build --release
          cd ./target/release
          ./webapp-bundler --input ../../../../../hoppscotch-selfhost-web/dist --output ../../../../bundle.zip --manifest ../../../../manifest.json

      - name: Run build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD : ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          args: ${{ matrix.args }}
          projectPath: "./packages/hoppscotch-desktop"

      #############################################
      ##     Move & upload release artifacts     ##
      #############################################

      - name: Move files (Windows)
        if: matrix.identifier == 'windows'
        shell: pwsh
        run: |
          Move-Item "packages\hoppscotch-desktop\src-tauri\target\release\bundle\msi\Hoppscotch_${{ needs.prepare.outputs.tag }}_x64_en-US.msi" "packages\hoppscotch-desktop\src-tauri\target\release\bundle\msi\Hoppscotch-amd64.msi"
          Move-Item "packages\hoppscotch-desktop\src-tauri\target\release\bundle\msi\Hoppscotch_${{ needs.prepare.outputs.tag }}_x64_en-US.msi.sig" "packages\hoppscotch-desktop\src-tauri\target\release\bundle\msi\Hoppscotch-amd64.msi.sig"
          Move-Item "packages\hoppscotch-desktop\src-tauri\target\release\bundle\nsis\Hoppscotch_${{ needs.prepare.outputs.tag }}_x64-setup.exe" "packages\hoppscotch-desktop\src-tauri\target\release\bundle\nsis\Hoppscotch-amd64-setup.exe"
          Move-Item "packages\hoppscotch-desktop\src-tauri\target\release\bundle\nsis\Hoppscotch_${{ needs.prepare.outputs.tag }}_x64-setup.exe.sig" "packages\hoppscotch-desktop\src-tauri\target\release\bundle\nsis\Hoppscotch-amd64-setup.exe.sig"
      - name: Upload files as artifacts (Windows)
        if: "!startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'windows'"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: |
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/msi/Hoppscotch-amd64.msi
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/msi/Hoppscotch-amd64.msi.sig
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/nsis/Hoppscotch-amd64-setup.exe
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/nsis/Hoppscotch-amd64-setup.exe.sig
      - name: Upload files to release (Windows)
        if: startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'windows'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/msi/Hoppscotch-amd64.msi
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/msi/Hoppscotch-amd64.msi.sig
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/nsis/Hoppscotch-amd64-setup.exe
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/nsis/Hoppscotch-amd64-setup.exe.sig

      - name: Move files (Linux)
        if: matrix.identifier == 'linux'
        run: |
          mv "packages/hoppscotch-desktop/src-tauri/target/release/bundle/deb/Hoppscotch_${{ needs.prepare.outputs.tag }}_amd64.deb" "packages/hoppscotch-desktop/src-tauri/target/release/bundle/deb/Hoppscotch-amd64.deb"
          mv "packages/hoppscotch-desktop/src-tauri/target/release/bundle/rpm/Hoppscotch_${{ needs.prepare.outputs.tag }}-x86_64.rpm" "packages/hoppscotch-desktop/src-tauri/target/release/bundle/rpm/Hoppscotch-amd64.rpm"
          mv "packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch_${{ needs.prepare.outputs.tag }}_amd64.AppImage" "packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch-amd64.AppImage"
          mv "packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch_${{ needs.prepare.outputs.tag }}_amd64.AppImage.sig" "packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch-amd64.AppImage.sig"
      - name: Upload files as artifacts (Linux)
        if: "!startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'linux'"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: |
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/deb/Hoppscotch-amd64.deb
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/rpm/Hoppscotch-amd64.rpm
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch-amd64.AppImage
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch-amd64.AppImage.sig
      - name: Upload files to release (Linux)
        if: startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'linux'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/deb/Hoppscotch-amd64.deb
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/rpm/Hoppscotch-amd64.rpm
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch-amd64.AppImage
            packages/hoppscotch-desktop/src-tauri/target/release/bundle/appimage/Hoppscotch-amd64.AppImage.sig

      - name: Move files (MacOS - ARM64)
        if: matrix.identifier == 'macos-aarch64'
        run: |
          mv "packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Hoppscotch_${{ needs.prepare.outputs.tag }}_aarch64.dmg" "packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Hoppscotch-aarch64.dmg"
          mv "packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch.app.tar.gz" "packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch-aarch64.app.tar.gz"
          mv "packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch.app.tar.gz.sig" "packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch-aarch64.app.tar.gz.sig"
      - name: Upload files as artifacts (MacOS - ARM64)
        if: "!startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'macos-aarch64'"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: |
            packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Hoppscotch-aarch64.dmg
            packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch-aarch64.app.tar.gz
            packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch-aarch64.app.tar.gz.sig
      - name: Upload files to release (MacOS - ARM64)
        if: startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'macos-aarch64'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/Hoppscotch-aarch64.dmg
            packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch-aarch64.app.tar.gz
            packages/hoppscotch-desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/macos/Hoppscotch-aarch64.app.tar.gz.sig

      - name: Move files (MacOS - AMD64)
        if: matrix.identifier == 'macos-amd64'
        run: |
          mv "packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/Hoppscotch_${{ needs.prepare.outputs.tag }}_x64.dmg" "packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/Hoppscotch-amd64.dmg"
          mv "packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch.app.tar.gz" "packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch-amd64.app.tar.gz"
          mv "packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch.app.tar.gz.sig" "packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch-amd64.app.tar.gz.sig"
      - name: Upload files as artifacts (MacOS - AMD64)
        if: "!startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'macos-amd64'"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: |
            packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/Hoppscotch-amd64.dmg
            packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch-amd64.app.tar.gz
            packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch-amd64.app.tar.gz.sig
      - name: Upload files to release (MacOS - ARM64)
        if: startsWith(github.event.ref, 'refs/tags/') && matrix.identifier == 'macos-amd64'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/dmg/Hoppscotch-amd64.dmg
            packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch-amd64.app.tar.gz
            packages/hoppscotch-desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/macos/Hoppscotch-amd64.app.tar.gz.sig

  # Update release.json
  release:
    if: startsWith(github.event.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ndhq/prepare-tauri-update-json
      - name: Install dependencies
        run: npm ci
      - name: Update release.json
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
